const PurpleColour = '#343990ff'

module.exports = {
  columns: [
    {
      id: 'EXPERIMENT_ID',
      label: 'Experiment ID',
      minWidth: 70,
      fontWeight: 'bold',
      backgroundColor: PurpleColour,
      color: '#efeff6ff',
    },
    {
      id: 'BATCH_ID',
      label: 'Batch ID',
      minWidth: 75,
      fontWeight: 'bold',
      backgroundColor: PurpleColour,
      color: '#efeff6ff',
    },
    {
      id: 'CRO',
      label: 'CRO',
      minWidth: 55,
      fontWeight: 'bold',
      backgroundColor: PurpleColour,
      color: '#efeff6ff',
    },
    {
      id: 'ASSAY_TYPE',
      label: 'Assay Type',
      minWidth: 65,
      align: 'right',
      fontWeight: 'bold',
      backgroundColor: PurpleColour,
      color: '#efeff6ff',
    },
    {
      id: 'CELL_LINE',
      label: 'Cell Line',
      minWidth: 65,
      align: 'right',
      fontWeight: 'bold',
      backgroundColor: PurpleColour,
      color: '#efeff6ff',
    },
    {
      id: 'VARIANT',
      label: 'Variant',
      minWidth: 65,
      align: 'right',
      fontWeight: 'bold',
      backgroundColor: PurpleColour,
      color: '#efeff6ff',
    },
    {
      id: 'IC50_NM',
      label: 'IC50 nM',
      minWidth: 60,
      fontWeight: 'bold',
      backgroundColor: PurpleColour,
      color: '#efeff6ff',
    },
    {
      id: 'GEOMEAN',
      label: 'Geomean nM',
      minWidth: 50,
      fontWeight: 'bold',
      backgroundColor: PurpleColour,
      color: '#efeff6ff',
    },
    {
      id: 'PCT_SERUM',
      label: '% Serum',
      minWidth: 60,
      fontWeight: 'bold',
      backgroundColor: PurpleColour,
      color: '#efeff6ff',
    },
    {
      id: 'THREED',
      label: '3D',
      minWidth: 50,
      fontWeight: 'bold',
      backgroundColor: PurpleColour,
      color: '#efeff6ff',
    },
    {
      id: 'TREATMENT',
      label: 'Treatment',
      minWidth: 60,
      fontWeight: 'bold',
      backgroundColor: PurpleColour,
      color: '#efeff6ff',
    },
    {
      id: 'PASSAGE_NUMBER',
      label: 'Passage #',
      minWidth: 50,
      fontWeight: 'bold',
      backgroundColor: PurpleColour,
      color: '#efeff6ff',
    },
    {
      id: 'WASHOUT',
      label: 'Washout',
      minWidth: 50,
      fontWeight: 'bold',
      backgroundColor: PurpleColour,
      color: '#efeff6ff',
    },
    {
      id: 'CELL_INCUBATION_HR',
      label: 'Cell Incu (hr)',
      minWidth: 60,
      fontWeight: 'bold',
      backgroundColor: PurpleColour,
      color: '#efeff6ff',
    },
    {
      id: 'PLOT',
      label: 'IC50 Plot',
      align: 'center',
      minWidth: 120,
      fontWeight: 'bold',
      backgroundColor: PurpleColour,
      color: '#efeff6ff',
    },
    {
      id: 'FLAG',
      label: 'Flag',
      minWidth: 50,
      align: 'right',
      fontWeight: 'bold',
      backgroundColor: PurpleColour,
      color: '#efeff6ff',
    },
  ],
}
