const PurpleColour = "#343990ff";

module.exports = {
  columns: [
    {
      id: "COMPOUND_ID",
      label: "Compound ID",
      minWidth: 90,
      fontWeight: "bold",
      backgroundColor: PurpleColour,
      color: "#efeff6ff",
    },
    {
      id: "CRO",
      label: "CRO",
      minWidth: 90,
      fontWeight: "bold",
      backgroundColor: PurpleColour,
      color: "#efeff6ff",
    },
    {
      id: "ASSAY_TYPE",
      label: "Assay Type",
      minWidth: 50,
      align: "right",
      fontWeight: "bold",
      backgroundColor: PurpleColour,
      color: "#efeff6ff",
    },
    {
      id: "TARGET",
      label: "Target",
      minWidth: 60,
      align: "right",
      fontWeight: "bold",
      backgroundColor: PurpleColour,
      color: "#efeff6ff",
    },
    {
      id: "VARIANT",
      label: "Variant",
      minWidth: 50,
      fontWeight: "bold",
      backgroundColor: PurpleColour,
      color: "#efeff6ff",
    },
    {
      id: "ATP_CONC_UM",
      label: "ATP Conc (uM)",
      minWidth: 40,
      fontWeight: "bold",
      backgroundColor: PurpleColour,
      color: "#efeff6ff",
    },
    {
      id: "COFACTORS",
      label: "Cofactors",
      minWidth: 50,
      fontWeight: "bold",
      backgroundColor: PurpleColour,
      color: "#efeff6ff",
    },
    {
      id: "GEOMEAN",
      label: "Geomean nM",
      minWidth: 50,
      align: "center",
      fontWeight: "bold",
      backgroundColor: PurpleColour,
      color: "#efeff6ff",
    },
    {
      id: "N_OF_M",
      label: "n of m",
      minWidth: 50,
      fontWeight: "bold",
      backgroundColor: PurpleColour,
      color: "#efeff6ff",
    },
    {
      id: "STDEV",
      label: "Stdev",
      align: "center",
      minWidth: 120,
      fontWeight: "bold",
      backgroundColor: PurpleColour,
      color: "#efeff6ff",
    },
  ],
};
