const PurpleColour = '#343990ff'

module.exports = {
  columns: [
    {
      id: 'COMPOUND_ID',
      label: 'Compound ID',
      minWidth: 60,
      fontWeight: 'bold',
      backgroundColor: PurpleColour,
      color: '#efeff6ff',
    },
    {
      id: 'CRO',
      label: 'CRO',
      minWidth: 50,
      fontWeight: 'bold',
      backgroundColor: PurpleColour,
      color: '#efeff6ff',
    },
    {
      id: 'ASSAY_TYPE',
      label: 'Assay Type',
      minWidth: 55,
      align: 'right',
      fontWeight: 'bold',
      backgroundColor: PurpleColour,
      color: '#efeff6ff',
    },
    {
      id: 'CELL_LINE',
      label: 'Cell Line',
      minWidth: 65,
      align: 'right',
      fontWeight: 'bold',
      backgroundColor: PurpleColour,
      color: '#efeff6ff',
    },
    {
      id: 'VARIANT',
      label: 'Variant',
      minWidth: 65,
      fontWeight: 'bold',
      backgroundColor: PurpleColour,
      color: '#efeff6ff',
    },
    {
      id: 'CELL_INCUBATION_HR',
      label: 'Cell Inc (hr)',
      minWidth: 60,
      fontWeight: 'bold',
      backgroundColor: PurpleColour,
      color: '#efeff6ff',
    },
    {
      id: 'PCT_SERUM',
      label: '% Serum',
      minWidth: 55,
      fontWeight: 'bold',
      backgroundColor: PurpleColour,
      color: '#efeff6ff',
    },
    {
      id: 'THREED',
      label: '3D',
      minWidth: 50,
      fontWeight: 'bold',
      backgroundColor: PurpleColour,
      color: '#efeff6ff',
    },
    {
      id: 'GEOMEAN',
      label: 'Geomean nM',
      minWidth: 70,
      fontWeight: 'bold',
      backgroundColor: PurpleColour,
      color: '#efeff6ff',
    },
    {
      id: 'N_OF_M',
      label: 'n of m',
      minWidth: 60,
      fontWeight: 'bold',
      backgroundColor: PurpleColour,
      color: '#efeff6ff',
    },
    {
      id: 'STDEV',
      label: 'Stdev',
      minWidth: 50,
      fontWeight: 'bold',
      backgroundColor: PurpleColour,
      color: '#efeff6ff',
    },
  ],
}
