// export const columns = [
module.exports = {
  columns: [
    {
      id: "EXPERIMENT_ID",
      label: "Experiment ID",
      minWidth: 90,
      fontWeight: "bold",
      backgroundColor: "#343990ff",
      color: "#efeff6ff",
    },
    {
      id: "BATCH_ID",
      label: "Batch ID",
      minWidth: 90,
      fontWeight: "bold",
      backgroundColor: "#343990ff",
      color: "#efeff6ff",
    },
    {
      id: "TARGET",
      label: "Target",
      minWidth: 50,
      align: "right",
      fontWeight: "bold",
      backgroundColor: "#343990ff",
      color: "#efeff6ff",
    },
    {
      id: "VARIANT",
      label: "Variant",
      minWidth: 60,
      align: "right",
      fontWeight: "bold",
      backgroundColor: "#343990ff",
      color: "#efeff6ff",
    },
    {
      id: "IC50_NM",
      label: "IC50 nM",
      minWidth: 50,
      fontWeight: "bold",
      backgroundColor: "#343990ff",
      color: "#efeff6ff",
    },
    {
      id: "GEOMEAN",
      label: "Geomean nM",
      minWidth: 50,
      fontWeight: "bold",
      backgroundColor: "#343990ff",
      color: "#efeff6ff",
    },
    {
      id: "COFACTORS",
      label: "Co-factors",
      minWidth: 60,
      fontWeight: "bold",
      backgroundColor: "#343990ff",
      color: "#efeff6ff",
    },
    {
      id: "ATP_CONC_UM",
      label: "ATP Conc uM",
      minWidth: 50,
      fontWeight: "bold",
      backgroundColor: "#343990ff",
      color: "#efeff6ff",
    },
    {
      id: "PLOT",
      label: "IC50 Plot",
      align: "center",
      minWidth: 120,
      fontWeight: "bold",
      backgroundColor: "#343990ff",
      color: "#efeff6ff",
    },
    {
      id: "FLAG",
      label: "Flag",
      minWidth: 50,
      align: "right",
      fontWeight: "bold",
      backgroundColor: "#343990ff",
      color: "#efeff6ff",
    },
  ],
};
